pwa:
    image_processor: 'pwa.image_processor.imagick'
    manifest:
        enabled: true
        background_color: "#c026d3"
        theme_color: "#c026d3"
        name: 'Simple White Noise App'
        short_name: 'noise'
        description: 'White noise, using Symfony'
        orientation: "any"
        display: "standalone"
        scope: "/"
        display_override: ['fullscreen', 'minimal-ui', 'window-controls-overlay']
        id: "/"
        start_url: "./?mode=standalone"
        icons:
            # https://www.veryicon.com/icons/miscellaneous/smart-site/noise-3.html
            - src: "images/noise-3-512.png"
              sizes: "any"
        screenshots:
            - "images/screenshot1.png"
            - "images/screenshot2.png"
        categories: []
        shortcuts: []
        edge_side_panel:
            preferred_width: 280
        widgets: []
    serviceworker:
        enabled: true
        src: "sw.js"
        skip_waiting: true
        workbox:
            asset_cache:
                regex: '/\.(css|js|json|xml|txt|mp3|map|webmanifest)$/'
#            resource_caches:
#                - regex: '\/pages\/.*$'
#                  cache_name: 'static-pages'
#                  strategy: 'cacheFirst'
##                  network_timeout: 2 # Wait only 2 seconds (only when strategy = networkFirst
#                  urls: # List of URLs to precache. The URL shall be comprised within the regex
#                      - 'app_terms_of_service'
#                      - 'app_about'
#                - regex: '\/articles\/.*$'
#                  cache_name: 'articles'
#                  strategy: 'staleWhileRevalidate'
#                  broadcast: true # Broadcast changes only when strategy = staleWhileRevalidate
#                  urls: # List of URLs to precache. The URL shall be comprised within the regex
##                      - 'app_articles'
#
##            warm_cache_urls:
##                - 'app_homepage'
###                - 'app_about'
            page_fallback: 'app_homepage'
