pwa:
    image_processor: 'pwa.image_processor.imagick'
    manifest:
        enabled: true
        background_color: "#c026d3"
        theme_color: "#c026d3"
        name: 'Simple White Noise App'
        short_name: 'todo'
        description: 'White noise, using Symfony'
        orientation: "any"
        display: "standalone"
        scope: "/"
        display_override: ['fullscreen', 'minimal-ui', 'window-controls-overlay']
        id: "/"
        start_url: "./"
        icons:
            # https://www.veryicon.com/icons/miscellaneous/smart-site/noise-3.html
            - src: "images/noise-3.svg"
              sizes: "any"
        screenshots:
            - "images/screenshot1.png"
            - "images/screenshot2.png"
        categories: []
        shortcuts: []
        edge_side_panel:
            preferred_width: 280
        widgets: []
    serviceworker:
        enabled: true
        src: "sw.js"
        skip_waiting: true
        workbox:
            warm_cache_urls:
                - 'app_homepage'
            page_fallback: 'app_homepage'
